In [1]:
from scipy.linalg import solve
import numpy as np

### Часть 1

__1.__ Исследовать на линейную зависимость:
$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$

#### Решение:

Можно заметить что 
$$f_1(x) = -f_4(x) - f_3(x) + f_2(x)$$
А раз $f_1$ можно выразить через $f_2$, $f_3$ и $f_4$, значит они линейно зависимы

__2.__ Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}.$$
#### Решение:
$$f_4(x) = (x+1)^2 = x^2 + 2x + 1 = f_{3}(x) + 2f_{2}(x) + \frac{f_{1}(x)}{2}$$
Значит $f_1$, $f_2$, $f_3$ и $f_4$ линейно зависимы

__3.__ Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.

#### Решение: 
решение очевидно, но все же запишем в матричном виде и решим используя метод `solve` пакета `scipy.linalg`

In [2]:
B = np.array([
    [0, 0, 10],
    [2, 0, 0],
    [0, 1, 0]]).T

X = np.array([2,3,5])

X_new = solve(B, X)

X_new

array([0.5, 1. , 3. ])

__4.__ Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

   а) в базисе $1$, $x$, $x^{2}$;

   б) в базисе $x^{2}$, $x-1$, $1$.

#### Решение:
Также, запишем базисы в матричном виде и решим

In [3]:
X = np.array([3, -2, 2])
B_a = np.array([
    [0,0,1],
    [0,1,0],
    [1,0,0]
]).T

B_b = np.array([
    [1,0,0],
    [0,1,-1],
    [0,0,1]
])


print(f'{solve(B_a, X)}, \n{solve(B_b, X)}')

[ 2. -2.  3.], 
[3. 0. 2.]


__5.__ Установить, является ли линейным подпространством:

а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;
    
б) все векторы, являющиеся линейными комбинациями данных векторов $\{u_{1}, u_{2}, ..., u_{n}\}$.

### Часть 2

__1.__ Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

#### Решение:

a)

In [4]:
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])

# np.dot(x,y)
x@y

33

б)

In [5]:
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])

np.dot(x,y)

-23

__2.__ Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.
#### Решение:


In [6]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])

a_norm = np.linalg.norm(a)
b_norm = np.linalg.norm(b)

cos_phi = np.dot(a, b) / a_norm / b_norm

print(f'нормы векторов: \na: {a_norm} \nb: {b_norm}')
print(f'Угол между векторами: {np.arccos(cos_phi)}')

нормы векторов: 
a: 6.0 
b: 13.0
Угол между векторами: 0.4568740035326613


__3.__ Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?
   

__4.__ Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>

Не образуют, так как не образуют базис в линейном прострастве $\mathbb{R}^{3}$:<br>

б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>

In [7]:
def is_perpenlicular(x1, x2, x3):
    """Возвращает True если попарное скалярное произведение векторов равно нулю"""
    return np.dot(x1,x2) == 0 and np.dot(x2,x3) == 0 and np.dot(x1,x3) == 0

In [8]:
x1 = np.array([1/np.sqrt(2), -1/np.sqrt(2), 0])
x2 = np.array([1/np.sqrt(2), 1/np.sqrt(2), 0])
x3 = np.array([0, 0, 1])
is_perpenlicular(x1, x2, x3)

True

в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>

In [9]:
x1 = np.array([1/2, -1/2, 0])
x2 = np.array([0,1/2, 1/2])
x3 = np.array([0, 0, 1])

is_perpenlicular(x1, x2, x3)

False

г) $(1,0,0),(0,1,0),(0,0,1)?$ 

In [10]:
x1 = np.array([1, 0, 0])
x2 = np.array([0, 1, 0])
x3 = np.array([0, 0, 1])

is_perpenlicular(x1, x2, x3)

True