In [1]:
import numpy as np

### Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B = \begin{pmatrix}
1 + 4 & -2 -1\\ 
3 + 0 & 0 + 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

$A \cdot B = 
\begin{pmatrix}
1 \cdot 4 -2 \cdot 0 & -1 \cdot 1 -2 \cdot 5\\ 
3 \cdot + 0 & -1 \cdot 3 + 0 \cdot 5
\end{pmatrix} = 
\begin{pmatrix}
4 & -11 \\ 
12 & -3
\end{pmatrix}
$

In [3]:
A = np.array([
    [1, -2],
    [3, 0]
])

B = np.array([
    [4, -1],
    [0, 5]
])

print(A+B)
print(A.dot(B))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

$$ 3A - 2B + 4C = 
3 \cdot \begin{pmatrix}
1 & 7 \\ 
3 & -6
\end{pmatrix}
- 2 \cdot \begin{pmatrix}
0 & 5 \\ 
2 & -1
\end{pmatrix}
+4 \cdot \begin{pmatrix}
2 & -4 \\ 
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3 - 0 + 8 & 21 - 10 - 16\\ 
9 - 4 + 4 & -18 + 2 + 4
\end{pmatrix} = 
\begin{pmatrix}
11 & -5 \\ 
9 & -12
\end{pmatrix}$$ 

In [4]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5], [2,-1]])
C = np.array([[2,-4], [1,1]])
print(3*A - 2*B + 4*C)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$ AA^{T} =
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot 
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = 
\begin{pmatrix}
16+1 & 20-2 & 8+3\\ 
20-2 & 25+4 & 10-6\\ 
8+3 & 10-6 & 4+9
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}
$

In [9]:
A = np.array([[4,1], [5,-2], [2,3]])
print(A.dot(A.T))
print(A.T.dot(A))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

### Часть 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = \sin^2x + \cos^2x = 1;$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4(5\cdot9 - 1\cdot0) - 2(0\cdot9 - 0\cdot1) + 3(0\cdot0 - 0\cdot5);$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1(5\cdot9 - 6\cdot8) -2(4\cdot9 - 6\cdot7) + 3(4\cdot8 - 5\cdot7) =$$
$$ = 45 - 48 - 72 + 84 + 96 - 105 = -3 - 72 + 84 - 9 =0$$

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = = det(A \cdot A) = det(A)\cdot det(A) = 16$;
    
   б) $det(A^{T}) = det(A) =4$;
    
   в) $det(2A) = 2 \cdot det(A) = 8$.
   

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

#### Решение
Сложив первую и вторую строки мы получим третью, значит ее можно исключить
$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$$
Также, тертий столбец является суммой первого и второго
$$\begin{pmatrix}
1 & 2 \\ 
1 & 1 
\end{pmatrix}$$
Значит ранг матрицы равен __2__

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$
#### Решение
Третья строка получается путем суммирования первых двух, а значит ее можно исключить.

$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\  
2 & 3 & 5 & 6
\end{pmatrix}$$

Также, первая и вторая столбцы линейно зависимы, а значит один из столбцов можно исключть

$$\begin{pmatrix}
0 & 2 & 1\\ 
0 & 2 & 2\\  
2 & 5 & 6
\end{pmatrix}$$

Итого, ранг матрицы равен __3__